version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
  db:
    build:
      context: ./
      dockerfile: db.Dockerfile
    ports:
      - 3208:3306
    volumes:
      - ./db/my.conf:/etc/mysql/conf.d/my.conf
      - ./db/db_init:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      BIND-ADDRESS: 0.0.0.0
